repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-added-large-files
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args: [--py38-plus]
      - id: pyupgrade
        name: pyupgrade (__main__.py)
        args: [--py38-plus, --keep-runtime-typing]
        files: .*\/__main__.py # We run ruff after pyugprade to remove unused imports
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
      - id: ruff # Run the linter.
        args: [--fix]
      - id: ruff # Sort improts
        name: sort imports with ruff
        args: [--select, I, --fix]
      - id: ruff-format # Run the formatter.

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.377
    hooks:
      - id: pyright
        additional_dependencies: # these dependencies are synced via the first hook
          - typing-extensions
          - numpy
          - pyclibrary
          - Pillow
          - pypng
          - pyside6
          - pyqtgraph
          - appdirs
          - scipy
          - scikit-image
          - colormath